Repository ramp4-pcar4/storylines, pull requests merged in 2024-11, with the labels that each got.

#500 Handle undefined slides
  package.json
  src/components/story/story.vue
  src/definitions.ts
Labels: PR: Active, PR: Frontend

#501 Add Slackbot
  .github/requirements.txt
  .github/slack-bot.py
  .github/workflows/slack-bot.yml
Labels: PR: Active, PR: Build

#504 Adjust grid teleport + mobile changes
  public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
  src/components/panels/map-panel.vue
  src/components/story/mobile-menu.vue
Labels: PR: Frontend

#505 add captions to map panels; adjust map layout to better fit titles and captions
  StoryRampSchema.json
  public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
  src/components/panels/helpers/point-of-interest-item.vue
  src/components/panels/map-panel.vue
  src/components/panels/panel.vue
  src/components/panels/slideshow-panel.vue
  src/definitions.ts
Labels: PR: Frontend

#511 Fix slackbot issues with double quotes
  .github/slack-bot.py
Labels: PR: Build
